
DROP TRIGGER deleteUser ON USERS;
DROP TRIGGER deleteGuild ON GUILDS;
DROP TRIGGER chiefLeave ON BELONGS;
DROP FUNCTION delUser();
DROP FUNCTION delGuild();
DROP FUNCTION chiefLeave();

-- Achievements
DROP TRIGGER tChiefGuild ON SCORES;
DROP TRIGGER tSaveTheWorld ON SCORES;
DROP TRIGGER tApprentiMath ON SCORES;
DROP TRIGGER tApprentice ON SCORES;
DROP TRIGGER tBaguette ON SCORES;
DROP TRIGGER tZombie ON SCORES;
DROP TRIGGER tCurry ON SCORES;
DROP TRIGGER tTeaTime ON SCORES;
DROP TRIGGER tChtulu ON SCORES;
DROP TRIGGER tMoon ON SCORES;
DROP TRIGGER tForeverAlone ON FRIENDS;
DROP TRIGGER tMafia ON SCORES;
DROP TRIGGER tManifProlo ON SCORES;
DROP TRIGGER tLoveIsReal ON FAVORITES;
DROP TRIGGER tPhilantrope ON BELONGS;
DROP FUNCTION chiefGuild();
DROP FUNCTION saveTheWorld();
DROP FUNCTION apprentiMath();
DROP FUNCTION apprentice();
DROP FUNCTION baguette();
DROP FUNCTION zombie();
DROP FUNCTION curry();
DROP FUNCTION teaTime();
DROP FUNCTION chtulu();
DROP FUNCTION moon();
DROP FUNCTION foreverAlone();
DROP FUNCTION mafia();
DROP FUNCTION manifProlo();
DROP FUNCTION loveIsReal();
DROP FUNCTION philantrope();


DROP RULE CONNECTION ON CONNECTED;
DROP RULE CHIEFBELONG ON GUILDS;

DROP VIEW CONNECTED;

DROP TABLE FAVORITES;
DROP TABLE BELONGS;
DROP TABLE ACHIEVED;
DROP TABLE FRIENDS;
DROP TABLE SCORES;
DROP TABLE LEVELS;
DROP TABLE WORLDS;
DROP TABLE GAMES;
DROP TABLE LESSONS;
DROP TABLE THEMES;
DROP TABLE GUILDS;
DROP TABLE USERS;
DROP TABLE ACHIEVEMENTS;

