DROP TABLE FAVORITES;
DROP TABLE BELONGS;
DROP TABLE ACHIEVED;
DROP TABLE FRIENDS;
DROP TABLE SCORES;
DROP TABLE LEVELS;
DROP TABLE WORLDS;
DROP TABLE GAMES;
DROP TABLE LESSONS;
DROP TABLE THEMES;
DROP TABLE GUILDS;
DROP TABLE USERS;
DROP TABLE ACHIEVEMENTS;

