
DROP TRIGGER deleteUser ON USERS;
DROP TRIGGER deleteGuild ON GUILDS;
DROP TRIGGER chiefLeave ON BELONGS;
DROP TRIGGER tSaveTheWorld ON SCORES;
DROP TRIGGER tApprentiMath ON SCORES;

DROP FUNCTION delUser();
DROP FUNCTION delGuild();
DROP FUNCTION chiefLeave();
DROP FUNCTION saveTheWorld();
DROP FUNCTION apprentiMath();

DROP RULE CONNECTION ON CONNECTED;
DROP RULE CHIEFBELONG ON GUILDS;

DROP RULE CHIEFGUILD ON GUILDS;
DROP RULE APPRENTICE ON SCORES;
DROP RULE BAGUETTE ON SCORES;
DROP RULE ZOMBIE ON SCORES;
DROP RULE CURRY ON SCORES;
DROP RULE TEATIME ON SCORES;
DROP RULE CHTULU ON SCORES;
DROP RULE MOON ON SCORES;
DROP RULE FOREVERALONE ON FRIENDS;
DROP RULE MAFIA ON SCORES;
DROP RULE MANIF ON SCORES;
DROP RULE LOVEISREAL ON FAVORITES;
DROP RULE PHILANTROPE ON BELONGS;

DROP VIEW CONNECTED;

DROP TABLE FAVORITES;
DROP TABLE BELONGS;
DROP TABLE ACHIEVED;
DROP TABLE FRIENDS;
DROP TABLE SCORES;
DROP TABLE LEVELS;
DROP TABLE WORLDS;
DROP TABLE GAMES;
DROP TABLE LESSONS;
DROP TABLE THEMES;
DROP TABLE GUILDS;
DROP TABLE USERS;
DROP TABLE ACHIEVEMENTS;

